### ISSUE TITLE
Example Intermodule Routing Request does not work

### ISSUE THREAD

**Issue by 1Maxnet1** [motis-project/motis-page#4]
### How to reproduce the issue:
I attached a simple python script, with which I tried to post the example-request and get a response.
See here: https://motis-project.de/docs/api/endpoint/intermodal.html#intermodal-routing-request for the request.
Response content:
`{
    "destination": {
        "target": ""
    },
    "content_type": "MotisError",
    "content": {
        "error_code": 2,
        "category": "motis::access",
        "reason": "access: station not found"
    },
    "id": 1
}
`
It would be awesome, if someone test this request with a known setup, as with the docs on the website, I cannot find a mistake in the given example request. So it may be outdated ?

Note: It is not about to troubleshoot my python-script, but about to check, whether the example is still right. When I tried the same request some weeks ago, it did work and I got a valid response.
Python-Script (needs to be renamed to .py file, as github does not allow to attache python-files.)
[test-json.txt](https://github.com/motis-project/motis-page/files/5917146/test-json.txt)

**Comment by felixguendling** [comment]
Looking at the response, it's obvious that your station ID was not valid ("station not found").

The reason is that europe.motis-project.de runs with the current trunk version which is not released yet. That is why the documentation is not updated yet.

europe.motis-project.de is using the new multi-timetable functionality where station IDs are prefixed. You can easily lookup station IDs on europe.motis-project.de in the web UI by searching for a station. The URL contains the station ID.

For example, the ID of "Zürich, Stampfenbachplatz" is now sbb_8591379 instead of 8591379. Olten has the ID delfi_000008500218. Changing these IDs should fix the "station not found" problem.

**Comment by 1Maxnet1** [comment]
> Looking at the response, it's obvious that your station ID was not valid ("station not found").
>
> The reason is that europe.motis-project.de runs with the current trunk version which is not released yet. That is why the documentation is not updated yet.

Okay, that's what I guessed was the issue. Then I will have a look whether I can contribute to update the documentation.

> europe.motis-project.de is using the new multi-timetable functionality where station IDs are prefixed. You can easily lookup station IDs on europe.motis-project.de in the web UI by searching for a station. The URL contains the station ID.
> 
> For example, the ID of "Zürich, Stampfenbachplatz" is now sbb_8591379 instead of 8591379. Olten has the ID delfi_000008500218. Changing these IDs should fix the "station not found" problem.

Thanks. Will give it a try. I would propose to let the issue open, until documentation is updated, or is it tracked somewhere else ?

**Comment by felixguendling** [comment]
I don't think that the query in the documentation is required to work with the demo server. This would require changing the timestamps all the time which is not something we will do. The only purpose of the query in the documentation is to illustrate the query format (in addition to the actual documentation). It's not an example in the sense that you can use it as a test query for the demo server without adjusting it.

Maybe it makes sense to prevent this issue by using station IDs that are obviously not contained in any timetable dataset and must be replaced before use.
