### ISSUE TITLE
Installation instructions for Linux still mention dependencies

### ISSUE THREAD

**Issue by 1Maxnet1** [motis-project/motis-page#6]
In the Update Blog post you mentioned that v0.5.2 would offer portable binaries without dependencies:
https://motis-project.de/release/2021/09/11/motis-tools-release.html

On the Installation page it is still mentioned to install some dependencies:
https://motis-project.de/docs/install#linux-installation-guide

Are they obsolete? If so let me know and I can offer to opoen a Pull request to remove them.

Best Regards

**Comment by felixguendling** [comment]
The section about installing dependencies on Linux is obsolete.
PR (with "closes #6" in the message) welcome :-)
